#!/usr/bin/sh

if [ -z "$1" ]; then
    echo "Usage: hunter start|stop"
    exit 1
fi

case $1 in
    "start")
        echo "Starting server..."
        sudo docker start hunter-mysql > /dev/null
        echo "Done."
        exit 0
        ;;
    "stop")
        echo "Stopping server..."
        sudo docker stop hunter-mysql > /dev/null
        echo "Done."
        exit 0
        ;;
esac

echo "Usage: hunter start|stop"
exit 1
;;
