#!/usr/bin/sh
webapp="$(dirname $0)/venv/bin/python3 $(dirname $0)/main.py"

if [ -z "$1" ]; then
    echo "Usage: hunter start|stop"
    exit 1
fi

case $1 in
    "start")
        echo "Starting server..."
        sudo docker start hunter-mysql
        $webapp 2>&1 >/dev/null &
        echo "Done."
        exit 0
        ;;
    "stop")
        echo "Stopping server..."
        sudo docker stop hunter-mysql
        kill $(ps -ax | grep "$webapp" | grep -v grep | awk '{print $1}')
        echo "Done."
        exit 0
        ;;
esac

echo "Usage: hunter start|stop"
exit 1
;;
